// ======================================================================
// \title  Stm32SpiDriver.cpp
// \author ivanlara
// \brief  HAL boundary for the STM32H7 SPI blocking master driver (real
//         hardware implementation, stm32h7 target only). This is the only
//         file in this driver allowed to include spi.h/HAL_SPI_*/
//         HAL_GPIO_* -- see Stm32SpiDriverStub.cpp for the host unit-test
//         stand-in.
// ======================================================================

#include <fprime-stm32/Drv/STM32SpiDriver/Stm32SpiDriver.hpp>
#include <Fw/Types/Assert.hpp>

#include "spi.h"

namespace {

//! Convert a HAL-free SpiInstance to the corresponding HAL handle. Only
//! Spi5 has a CubeMX-generated handle in this project today. Re-resolved
//! on every hw* call (not cached) so multiple Stm32SpiDriver instances
//! never share any file-scope HAL state.
SPI_HandleTypeDef* toHalHandle(Stm32::SpiInstance instance) {
    //! The cases for each SPI instance. If your project uses additional instances,
    //! you need to add them here and ensure the corresponding HAL handle is returned, after
    //! you update the files from CubeMX autogenerated code into Hardware/stm32h753_hal/Core/Src/spi.c.
    SPI_HandleTypeDef* deviceHandle = nullptr;

    switch (instance) {
        case Stm32::SpiInstance::Spi1:
            #if SPI1_INSTANCE
            deviceHandle = &hspi1;
            #endif
            break;
        case Stm32::SpiInstance::Spi2:
            #if SPI2_INSTANCE
            deviceHandle = &hspi2;
            #endif
            break;
        case Stm32::SpiInstance::Spi3:
            #if SPI3_INSTANCE
            deviceHandle = &hspi3;
            #endif
            break;
        case Stm32::SpiInstance::Spi4:
            #if SPI4_INSTANCE
            deviceHandle = &hspi4;
            #endif
            break;
        case Stm32::SpiInstance::Spi5:
            #if SPI5_INSTANCE
            deviceHandle = &hspi5;
            #endif
            break;
        case Stm32::SpiInstance::Spi6:
            #if SPI6_INSTANCE
            deviceHandle = &hspi6;
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
    return deviceHandle;
}

//! Call the CubeMX-generated init function for the selected instance.
void callInstanceInit(Stm32::SpiInstance instance) {
    //! The cases for each SPI instance. If your project uses additional instances,
    //! you need to add the corresponding initialization function, just after you
    //! update the files from CubeMX autogenerated code into Hardware/stm32h753_hal/Core/Src/spi.c.
    switch (instance) {
        case Stm32::SpiInstance::Spi1:
            #if SPI1_INSTANCE
            MX_SPI1_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi2:
            #if SPI2_INSTANCE
            MX_SPI2_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi3:
            #if SPI3_INSTANCE
            MX_SPI3_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi4:
            #if SPI4_INSTANCE
            MX_SPI4_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi5:
            #if SPI5_INSTANCE
            MX_SPI5_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi6:
            #if SPI6_INSTANCE
            MX_SPI6_Init();
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
}

//! Map a HAL-free GpioPort identifier to the real CMSIS peripheral base.
//! Duplicated from Stm32GpioDriver.cpp's own file-scope helper of the same
//! shape -- no shared HAL-utility header exists in this library for
//! drivers to pull a mapping like this from, and every real driver .cpp in
//! this codebase is already self-contained rather than depending on
//! another driver's translation unit.
GPIO_TypeDef* toHalPort(Stm32::GpioPort port) {
    switch (port) {
        case Stm32::GpioPort::A:
            return GPIOA;
        case Stm32::GpioPort::B:
            return GPIOB;
        case Stm32::GpioPort::C:
            return GPIOC;
        case Stm32::GpioPort::D:
            return GPIOD;
        case Stm32::GpioPort::E:
            return GPIOE;
        case Stm32::GpioPort::F:
            return GPIOF;
        case Stm32::GpioPort::G:
            return GPIOG;
        case Stm32::GpioPort::H:
            return GPIOH;
        case Stm32::GpioPort::I:
            return GPIOI;
        case Stm32::GpioPort::J:
            return GPIOJ;
        case Stm32::GpioPort::K:
            return GPIOK;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(port));
            return nullptr;
    }
}

//! Enable the AHB4 clock for whichever GPIO port is passed in.
void enableGpioClock(GPIO_TypeDef* port) {
    FW_ASSERT(port != nullptr);

    if (port == GPIOA) {
        __HAL_RCC_GPIOA_CLK_ENABLE();
    } else if (port == GPIOB) {
        __HAL_RCC_GPIOB_CLK_ENABLE();
    } else if (port == GPIOC) {
        __HAL_RCC_GPIOC_CLK_ENABLE();
    } else if (port == GPIOD) {
        __HAL_RCC_GPIOD_CLK_ENABLE();
    } else if (port == GPIOE) {
        __HAL_RCC_GPIOE_CLK_ENABLE();
    } else if (port == GPIOF) {
        __HAL_RCC_GPIOF_CLK_ENABLE();
    } else if (port == GPIOG) {
        __HAL_RCC_GPIOG_CLK_ENABLE();
    } else if (port == GPIOH) {
        __HAL_RCC_GPIOH_CLK_ENABLE();
    } else if (port == GPIOI) {
        __HAL_RCC_GPIOI_CLK_ENABLE();
    } else if (port == GPIOJ) {
        __HAL_RCC_GPIOJ_CLK_ENABLE();
    } else if (port == GPIOK) {
        __HAL_RCC_GPIOK_CLK_ENABLE();
    } else {
        FW_ASSERT(false, reinterpret_cast<FwAssertArgType>(port));
    }
}

}  // namespace

namespace Stm32 {

Fw::Success Stm32SpiDriver ::open(SpiInstance instance, Stm32::GpioPort csPort, U16 csPin, U32 timeoutMs) {
    SPI_HandleTypeDef* const halHandle = toHalHandle(instance);
    FW_ASSERT(halHandle != nullptr, static_cast<FwAssertArgType>(instance));

    // MX_SPIn_Init() traps in Error_Handler() on failure rather than
    // returning a status (matches every other CubeMX-generated
    // MX_*_Init() in this project).
    callInstanceInit(instance);

    // SPI5 is configured NSS_SOFT: the HAL never drives a CS pin on its
    // own, so this driver owns the chip-select GPIO directly. Idle state
    // is HIGH (deselected) so the device is never accidentally selected
    // before the first transfer.
    GPIO_TypeDef* const halPort = toHalPort(csPort);
    FW_ASSERT(halPort != nullptr, static_cast<FwAssertArgType>(csPort));
    enableGpioClock(halPort);
    HAL_GPIO_WritePin(halPort, csPin, GPIO_PIN_SET);

    GPIO_InitTypeDef init = {};
    init.Pin = csPin;
    init.Mode = GPIO_MODE_OUTPUT_PP;
    init.Pull = GPIO_NOPULL;
    init.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(halPort, &init);

    this->m_instance = instance;
    this->m_csPort = csPort;
    this->m_csPin = csPin;
    this->m_timeoutMs = timeoutMs;
    this->m_opened = true;

    Fw::LogStringArg _instanceArg(instance == Stm32::SpiInstance::Spi1 ? "Spi1" :
                                  instance == Stm32::SpiInstance::Spi2 ? "Spi2" :
                                  instance == Stm32::SpiInstance::Spi3 ? "Spi3" :
                                  instance == Stm32::SpiInstance::Spi4 ? "Spi4" :
                                  instance == Stm32::SpiInstance::Spi5 ? "Spi5" :
                                  instance == Stm32::SpiInstance::Spi6 ? "Spi6" : "Unknown");
    this->log_ACTIVITY_HI_PortOpened(_instanceArg);
    return Fw::Success::SUCCESS;
}

void Stm32SpiDriver ::hwSetCs(bool active) {
    GPIO_TypeDef* const halPort = toHalPort(this->m_csPort);
    FW_ASSERT(halPort != nullptr);
    HAL_GPIO_WritePin(halPort, this->m_csPin, active ? GPIO_PIN_RESET : GPIO_PIN_SET);
}

I32 Stm32SpiDriver ::hwTransmitReceive(const U8* txData, U8* rxData, FwSizeType size) {
    SPI_HandleTypeDef* const halHandle = toHalHandle(this->m_instance);
    FW_ASSERT(halHandle != nullptr);
    FW_ASSERT(txData != nullptr);
    FW_ASSERT(rxData != nullptr);

    const HAL_StatusTypeDef status =
        HAL_SPI_TransmitReceive(halHandle, const_cast<U8*>(txData), rxData, static_cast<uint16_t>(size),
                                 this->m_timeoutMs);
    return static_cast<I32>(status);
}

}  // namespace Stm32
