// ======================================================================
// \title  Stm32SpiDriver.cpp
// \author ivanlara
// \brief  HAL boundary for the STM32H7 SPI blocking master driver (real
//         hardware implementation, stm32h7 target only). This is the only
//         file in this driver allowed to include spi.h/HAL_SPI_*/
//         HAL_GPIO_* -- see Stm32SpiDriverStub.cpp for the host unit-test
//         stand-in.
// ======================================================================

#include <fprime-stm32/Drv/STM32SpiDriver/Stm32SpiDriver.hpp>
#include <Fw/Types/Assert.hpp>
#include <Os/RawTime.hpp>

#include "CacheMaintenance.hpp"
#include "dma.h"
#include "spi.h"

namespace {

//! Convert a HAL-free SpiInstance to the corresponding HAL handle. Only
//! Spi5 has a CubeMX-generated handle in this project today. Re-resolved
//! on every hw* call (not cached) so multiple Stm32SpiDriver instances
//! never share any file-scope HAL state.
SPI_HandleTypeDef* toHalHandle(Stm32::SpiInstance instance) {
    //! The cases for each SPI instance. If your project uses additional instances,
    //! you need to add them here and ensure the corresponding HAL handle is returned, after
    //! you update the files from CubeMX autogenerated code into Hardware/stm32h753_hal/Core/Src/spi.c.
    SPI_HandleTypeDef* deviceHandle = nullptr;

    switch (instance) {
        case Stm32::SpiInstance::Spi1:
            #if SPI1_INSTANCE
            deviceHandle = &hspi1;
            #endif
            break;
        case Stm32::SpiInstance::Spi2:
            #if SPI2_INSTANCE
            deviceHandle = &hspi2;
            #endif
            break;
        case Stm32::SpiInstance::Spi3:
            #if SPI3_INSTANCE
            deviceHandle = &hspi3;
            #endif
            break;
        case Stm32::SpiInstance::Spi4:
            #if SPI4_INSTANCE
            deviceHandle = &hspi4;
            #endif
            break;
        case Stm32::SpiInstance::Spi5:
            #if SPI5_INSTANCE
            deviceHandle = &hspi5;
            #endif
            break;
        case Stm32::SpiInstance::Spi6:
            #if SPI6_INSTANCE
            deviceHandle = &hspi6;
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
    return deviceHandle;
}

//! Call the CubeMX-generated init function for the selected instance.
void callInstanceInit(Stm32::SpiInstance instance) {
    //! The cases for each SPI instance. If your project uses additional instances,
    //! you need to add the corresponding initialization function, just after you
    //! update the files from CubeMX autogenerated code into Hardware/stm32h753_hal/Core/Src/spi.c.
    switch (instance) {
        case Stm32::SpiInstance::Spi1:
            #if SPI1_INSTANCE
            MX_SPI1_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi2:
            #if SPI2_INSTANCE
            MX_SPI2_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi3:
            #if SPI3_INSTANCE
            MX_SPI3_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi4:
            #if SPI4_INSTANCE
            MX_SPI4_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi5:
            #if SPI5_INSTANCE
            MX_SPI5_Init();
            #endif
            break;
        case Stm32::SpiInstance::Spi6:
            #if SPI6_INSTANCE
            MX_SPI6_Init();
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
}

//! Map a HAL-free GpioPort identifier to the real CMSIS peripheral base.
//! Duplicated from Stm32GpioDriver.cpp's own file-scope helper of the same
//! shape -- no shared HAL-utility header exists in this library for
//! drivers to pull a mapping like this from, and every real driver .cpp in
//! this codebase is already self-contained rather than depending on
//! another driver's translation unit.
GPIO_TypeDef* toHalPort(Stm32::GpioPort port) {
    switch (port) {
        case Stm32::GpioPort::A:
            return GPIOA;
        case Stm32::GpioPort::B:
            return GPIOB;
        case Stm32::GpioPort::C:
            return GPIOC;
        case Stm32::GpioPort::D:
            return GPIOD;
        case Stm32::GpioPort::E:
            return GPIOE;
        case Stm32::GpioPort::F:
            return GPIOF;
        case Stm32::GpioPort::G:
            return GPIOG;
        case Stm32::GpioPort::H:
            return GPIOH;
        case Stm32::GpioPort::I:
            return GPIOI;
        case Stm32::GpioPort::J:
            return GPIOJ;
        case Stm32::GpioPort::K:
            return GPIOK;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(port));
            return nullptr;
    }
}

//! Enable the AHB4 clock for whichever GPIO port is passed in.
void enableGpioClock(GPIO_TypeDef* port) {
    FW_ASSERT(port != nullptr);

    if (port == GPIOA) {
        __HAL_RCC_GPIOA_CLK_ENABLE();
    } else if (port == GPIOB) {
        __HAL_RCC_GPIOB_CLK_ENABLE();
    } else if (port == GPIOC) {
        __HAL_RCC_GPIOC_CLK_ENABLE();
    } else if (port == GPIOD) {
        __HAL_RCC_GPIOD_CLK_ENABLE();
    } else if (port == GPIOE) {
        __HAL_RCC_GPIOE_CLK_ENABLE();
    } else if (port == GPIOF) {
        __HAL_RCC_GPIOF_CLK_ENABLE();
    } else if (port == GPIOG) {
        __HAL_RCC_GPIOG_CLK_ENABLE();
    } else if (port == GPIOH) {
        __HAL_RCC_GPIOH_CLK_ENABLE();
    } else if (port == GPIOI) {
        __HAL_RCC_GPIOI_CLK_ENABLE();
    } else if (port == GPIOJ) {
        __HAL_RCC_GPIOJ_CLK_ENABLE();
    } else if (port == GPIOK) {
        __HAL_RCC_GPIOK_CLK_ENABLE();
    } else {
        FW_ASSERT(false, reinterpret_cast<FwAssertArgType>(port));
    }
}

}  // namespace

namespace {

//! Callback registry: HAL_SPI_TxRxCpltCallback()/HAL_SPI_ErrorCallback() are
//! free functions with no user-context pointer, only a raw
//! SPI_HandleTypeDef*, so mapping back to "which Stm32SpiDriver instance
//! owns this handle" needs a table rather than a single cached pointer --
//! same reasoning and shape as Stm32UartDriver.cpp's s_uartRegistry. Only
//! instances opened in DMA mode are registered; a POLLED instance never
//! triggers these callbacks.
constexpr FwSizeType SPI_INSTANCE_CAPACITY = 6;  // SpiInstance::Spi1..Spi6

struct SpiRegistryEntry {
    SPI_HandleTypeDef* handle = nullptr;
    Stm32::Stm32SpiDriver* component = nullptr;
};

SpiRegistryEntry s_spiRegistry[SPI_INSTANCE_CAPACITY];

//! Look up which live Stm32SpiDriver instance (if any) owns `hspi`, by
//! linear scan of the small (<=6-entry) registry.
Stm32::Stm32SpiDriver* findSpiComponent(SPI_HandleTypeDef* hspi) {
    for (FwSizeType i = 0; i < SPI_INSTANCE_CAPACITY; i++) {
        if (s_spiRegistry[i].handle == hspi && s_spiRegistry[i].component != nullptr) {
            return s_spiRegistry[i].component;
        }
    }
    return nullptr;
}

}  // namespace

extern "C" void HAL_SPI_TxRxCpltCallback(SPI_HandleTypeDef* hspi) {
    FW_ASSERT(hspi != nullptr);
    Stm32::Stm32SpiDriver* const component = findSpiComponent(hspi);
    if (component != nullptr) {
        component->signalDmaComplete();
    }
}

extern "C" void HAL_SPI_ErrorCallback(SPI_HandleTypeDef* hspi) {
    FW_ASSERT(hspi != nullptr);
    Stm32::Stm32SpiDriver* const component = findSpiComponent(hspi);
    if (component != nullptr) {
        component->signalDmaError(hspi->ErrorCode);
    }
}

namespace Stm32 {

Fw::Success Stm32SpiDriver ::open(SpiInstance instance,
                                   Stm32::GpioPort csPort,
                                   U16 csPin,
                                   U32 timeoutMs,
                                   TransferMode mode) {
    SPI_HandleTypeDef* const halHandle = toHalHandle(instance);
    FW_ASSERT(halHandle != nullptr, static_cast<FwAssertArgType>(instance));

    // DMA1 clock/NVIC must be enabled before HAL_SPI_MspInit() links a DMA
    // stream to this instance (mirrors Stm32UartDriver.cpp's hwOpen()).
    // Idempotent to call even when this instance stays POLLED-only, and
    // harmless if another already-open driver (e.g. the USART1 comms link)
    // already ran it.
    if (mode == TransferMode::DMA) {
        MX_DMA_Init();
    }

    // MX_SPIn_Init() traps in Error_Handler() on failure rather than
    // returning a status (matches every other CubeMX-generated
    // MX_*_Init() in this project).
    callInstanceInit(instance);

    // SPI5 is configured NSS_SOFT: the HAL never drives a CS pin on its
    // own, so this driver owns the chip-select GPIO directly. Idle state
    // is HIGH (deselected) so the device is never accidentally selected
    // before the first transfer.
    GPIO_TypeDef* const halPort = toHalPort(csPort);
    FW_ASSERT(halPort != nullptr, static_cast<FwAssertArgType>(csPort));
    enableGpioClock(halPort);
    HAL_GPIO_WritePin(halPort, csPin, GPIO_PIN_SET);

    GPIO_InitTypeDef init = {};
    init.Pin = csPin;
    init.Mode = GPIO_MODE_OUTPUT_PP;
    init.Pull = GPIO_NOPULL;
    init.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(halPort, &init);

    this->m_instance = instance;
    this->m_csPort = csPort;
    this->m_csPin = csPin;
    this->m_timeoutMs = timeoutMs;
    this->m_transferMode = mode;
    this->m_opened = true;

    if (mode == TransferMode::DMA) {
        // This project's current CubeMX configuration for SPI5 has no DMA
        // request attached (see lib/fprime-stm32/src/spi.c's
        // HAL_SPI_MspInit() -- no __HAL_LINKDMA() call), so hdmatx/hdmarx
        // are null and HAL_SPI_TransmitReceive_DMA() would dereference a
        // null DMA handle. Assert loudly here instead of crashing
        // mid-transfer: regenerate the CubeMX project with a DMA request
        // added to this SPI instance before opening it in DMA mode.
        FW_ASSERT(halHandle->hdmatx != nullptr, static_cast<FwAssertArgType>(instance));
        FW_ASSERT(halHandle->hdmarx != nullptr, static_cast<FwAssertArgType>(instance));

        // Registered by instance index (bounds-safe: the enum itself can't
        // index outside the table), not a single shared pointer -- lets a
        // second, simultaneously-open DMA instance route its completion/
        // error callbacks correctly without disturbing this one's.
        FW_ASSERT(static_cast<FwSizeType>(instance) < SPI_INSTANCE_CAPACITY, static_cast<FwAssertArgType>(instance));
        s_spiRegistry[static_cast<FwSizeType>(instance)] = {halHandle, this};
    }

    Fw::LogStringArg _instanceArg(instance == Stm32::SpiInstance::Spi1 ? "Spi1" :
                                  instance == Stm32::SpiInstance::Spi2 ? "Spi2" :
                                  instance == Stm32::SpiInstance::Spi3 ? "Spi3" :
                                  instance == Stm32::SpiInstance::Spi4 ? "Spi4" :
                                  instance == Stm32::SpiInstance::Spi5 ? "Spi5" :
                                  instance == Stm32::SpiInstance::Spi6 ? "Spi6" : "Unknown");
    this->log_ACTIVITY_HI_PortOpened(_instanceArg);
    return Fw::Success::SUCCESS;
}

void Stm32SpiDriver ::hwSetCs(bool active) {
    GPIO_TypeDef* const halPort = toHalPort(this->m_csPort);
    FW_ASSERT(halPort != nullptr);
    HAL_GPIO_WritePin(halPort, this->m_csPin, active ? GPIO_PIN_RESET : GPIO_PIN_SET);
}

I32 Stm32SpiDriver ::hwTransmitReceive(const U8* txData, U8* rxData, FwSizeType size) {
    SPI_HandleTypeDef* const halHandle = toHalHandle(this->m_instance);
    FW_ASSERT(halHandle != nullptr);
    FW_ASSERT(txData != nullptr);
    FW_ASSERT(rxData != nullptr);

    if (this->m_transferMode == TransferMode::POLLED) {
        const HAL_StatusTypeDef status =
            HAL_SPI_TransmitReceive(halHandle, const_cast<U8*>(txData), rxData, static_cast<uint16_t>(size),
                                     this->m_timeoutMs);
        return static_cast<I32>(status);
    }

    // DMA path: buffers must be reachable by the DMA controller (not DTCM)
    // and the D-cache must be clean/invalidated around the transfer so the
    // CPU and DMA controller agree on what's actually in RAM.
    Stm32::AssertDmaSafe(txData, size);
    Stm32::AssertDmaSafe(rxData, size);
    Stm32::CleanDCacheForDma(txData, size);

    this->m_dmaBusy = true;
    this->m_dmaErrorCode = 0;
    const HAL_StatusTypeDef startStatus =
        HAL_SPI_TransmitReceive_DMA(halHandle, const_cast<U8*>(txData), rxData, static_cast<uint16_t>(size));
    if (startStatus != HAL_OK) {
        this->m_dmaBusy = false;
        return static_cast<I32>(startStatus);
    }

    // Block the caller until HAL_SPI_TxRxCpltCallback()/HAL_SPI_ErrorCallback()
    // clears m_dmaBusy, or this transfer's own watchdog expires -- this is
    // what lets DMA mode keep SpiWriteRead's synchronous port contract.
    Os::RawTime dmaStart;
    (void)dmaStart.now();
    const U32 timeoutUs = this->m_timeoutMs * 1000U;
    constexpr U32 MAX_DMA_POLL_ITERATIONS = 1000000U;  // hard backstop; the time check below is the real bound
    for (U32 i = 0; this->m_dmaBusy && (i < MAX_DMA_POLL_ITERATIONS); i++) {
        Os::RawTime now;
        (void)now.now();
        U32 elapsedUs = 0;
        (void)now.getDiffUsec(dmaStart, elapsedUs);
        if (elapsedUs >= timeoutUs) {
            break;
        }
    }

    if (this->m_dmaBusy) {
        (void)HAL_SPI_Abort(halHandle);
        this->m_dmaBusy = false;
        return static_cast<I32>(HAL_TIMEOUT);
    }

    Stm32::InvalidateDCacheForDma(rxData, size);
    return (this->m_dmaErrorCode == 0) ? static_cast<I32>(HAL_OK) : static_cast<I32>(HAL_ERROR);
}

}  // namespace Stm32
