// ======================================================================
// \title  Stm32I2cDriver.cpp
// \author ivanlara
// \brief  HAL boundary for the STM32H7 I2C blocking master driver (real
//         hardware implementation, stm32h7 target only). This is the only
//         file in this driver allowed to include i2c.h/HAL_I2C_* -- see
//         Stm32I2cDriverStub.cpp for the host unit-test stand-in.
// ======================================================================

#include <fprime-stm32/Drv/STM32I2cDriver/Stm32I2cDriver.hpp>
#include <Fw/Types/Assert.hpp>
#include <Os/RawTime.hpp>

#include "CacheMaintenance.hpp"
#include "dma.h"
#include "i2c.h"

namespace {

// CubeMX-computed I2C1 Timing register presets for this project's actual D2PCLK1 peripheral clock.
constexpr uint32_t I2C_TIMING_STANDARD_100KHZ = 0x307075B1U;
constexpr uint32_t I2C_TIMING_FAST_400KHZ = 0x00B03FDBU;
constexpr uint32_t I2C_TIMING_FASTPLUS_1MHZ = 0x0050174FU;

//! Convert a HAL-free I2cInstance to the corresponding HAL handle. Only
//! I2c1 has a CubeMX-generated handle in this project today.
I2C_HandleTypeDef* toHalHandle(Stm32::I2cInstance instance) {
    //! The cases for each I2C instance. If your project uses additional instances,
    //! you need to add them here and ensure the corresponding HAL handle is returned, after
    //! you update the files from CubeMX autogenerated code into lib/fprime-stm32/src/i2c.c.
    I2C_HandleTypeDef* deviceHandle = nullptr;

    switch (instance) {
        case Stm32::I2cInstance::I2c1:
            #if I2C1_INSTANCE
            deviceHandle = &hi2c1;
            #endif
            break;
        case Stm32::I2cInstance::I2c2:
            #if I2C2_INSTANCE
            deviceHandle = &hi2c2;
            #endif
            break;
        case Stm32::I2cInstance::I2c3:
            #if I2C3_INSTANCE
            deviceHandle = &hi2c3;
            #endif
            break;
        case Stm32::I2cInstance::I2c4:
            #if I2C4_INSTANCE
            deviceHandle = &hi2c4;
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
    return deviceHandle;
}

//! Call the CubeMX-generated init function for the selected instance.
void callInstanceInit(Stm32::I2cInstance instance) {
    //! The cases for each I2C instance. If your project uses additional instances,
    //! you need to add the correspondent Initialization fuction, just after you 
    //! update the files from CubeMX autogenerated code into lib/fprime-stm32/src/i2c.c.
    switch (instance) {
        case Stm32::I2cInstance::I2c1:
            #if I2C1_INSTANCE
            MX_I2C1_Init();
            #endif
            break;
        case Stm32::I2cInstance::I2c2:
            #if I2C2_INSTANCE
            MX_I2C2_Init();
            #endif
            break;
        case Stm32::I2cInstance::I2c3:
            #if I2C3_INSTANCE
            MX_I2C3_Init();
            #endif
            break;
        case Stm32::I2cInstance::I2c4:
            #if I2C4_INSTANCE
            MX_I2C4_Init();
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
}

//! Map a requested bus speed preset to its CubeMX-computed Timing value.
uint32_t toTiming(Stm32::I2cBusSpeed busSpeed) {
    switch (busSpeed) {
        case Stm32::I2cBusSpeed::Standard:
            return I2C_TIMING_STANDARD_100KHZ;
        case Stm32::I2cBusSpeed::Fast:
            return I2C_TIMING_FAST_400KHZ;
        case Stm32::I2cBusSpeed::FastPlus:
            return I2C_TIMING_FASTPLUS_1MHZ;
        default:
            return I2C_TIMING_FAST_400KHZ;
    }
}

}  // namespace

namespace {

constexpr FwSizeType I2C_INSTANCE_CAPACITY = 4;  // I2cInstance::I2c1..I2c4

struct I2cRegistryEntry {
    I2C_HandleTypeDef* handle = nullptr;
    Stm32::Stm32I2cDriver* component = nullptr;
};

I2cRegistryEntry s_i2cRegistry[I2C_INSTANCE_CAPACITY];

//! Look up which live Stm32I2cDriver instance (if any) owns `hi2c`, by
//! linear scan of the small (<=4-entry) registry.
Stm32::Stm32I2cDriver* findI2cComponent(I2C_HandleTypeDef* hi2c) {
    for (FwSizeType i = 0; i < I2C_INSTANCE_CAPACITY; i++) {
        if (s_i2cRegistry[i].handle == hi2c && s_i2cRegistry[i].component != nullptr) {
            return s_i2cRegistry[i].component;
        }
    }
    return nullptr;
}

}  // namespace

extern "C" void HAL_I2C_MasterTxCpltCallback(I2C_HandleTypeDef* hi2c) {
    FW_ASSERT(hi2c != nullptr);
    Stm32::Stm32I2cDriver* const component = findI2cComponent(hi2c);
    if (component != nullptr) {
        component->signalDmaComplete();
    }
}

extern "C" void HAL_I2C_MasterRxCpltCallback(I2C_HandleTypeDef* hi2c) {
    FW_ASSERT(hi2c != nullptr);
    Stm32::Stm32I2cDriver* const component = findI2cComponent(hi2c);
    if (component != nullptr) {
        component->signalDmaComplete();
    }
}

extern "C" void HAL_I2C_ErrorCallback(I2C_HandleTypeDef* hi2c) {
    FW_ASSERT(hi2c != nullptr);
    Stm32::Stm32I2cDriver* const component = findI2cComponent(hi2c);
    if (component != nullptr) {
        component->signalDmaError(hi2c->ErrorCode);
    }
}

namespace Stm32 {

Fw::Success Stm32I2cDriver ::open(I2cInstance instance, I2cBusSpeed busSpeed, TransferMode mode) {
    I2C_HandleTypeDef* const halHandle = toHalHandle(instance);
    FW_ASSERT(halHandle != nullptr, static_cast<FwAssertArgType>(instance));

    // DMA1 clock/NVIC must be enabled before HAL_I2C_MspInit() links a DMA stream to this instance.
    if (mode == TransferMode::DMA) {
        MX_DMA_Init();
    }

    // MX_I2Cn_Init() traps in Error_Handler() on failure rather than
    // returning a status (matches every other CubeMX-generated
    // MX_*_Init() in this project).
    callInstanceInit(instance);

    const uint32_t timing = toTiming(busSpeed);
    if (timing != halHandle->Init.Timing) {
        halHandle->Init.Timing = timing;
        if (HAL_I2C_Init(halHandle) != HAL_OK) {
            return Fw::Success::FAILURE;
        }
    }

    this->m_instance = instance;
    this->m_transferMode = mode;
    this->m_opened = true;

    if (mode == TransferMode::DMA) {
        FW_ASSERT(halHandle->hdmatx != nullptr, static_cast<FwAssertArgType>(instance));
        FW_ASSERT(halHandle->hdmarx != nullptr, static_cast<FwAssertArgType>(instance));

        FW_ASSERT(static_cast<FwSizeType>(instance) < I2C_INSTANCE_CAPACITY, static_cast<FwAssertArgType>(instance));
        s_i2cRegistry[static_cast<FwSizeType>(instance)] = {halHandle, this};
    }

    Fw::LogStringArg _speedArg(busSpeed == Stm32::I2cBusSpeed::Standard ? "Standard" :
                               busSpeed == Stm32::I2cBusSpeed::Fast ? "Fast" :
                               busSpeed == Stm32::I2cBusSpeed::FastPlus ? "FastPlus" : "Unknown");
    
    this->log_ACTIVITY_HI_PortOpened(_speedArg);
    return Fw::Success::SUCCESS;
}

namespace {

//! Block the calling thread until signalDmaComplete()/signalDmaError() clears `dmaBusy`, or `timeoutMs` elapses.
bool waitForI2cDma(volatile bool& dmaBusy, U32 timeoutMs) {
    Os::RawTime dmaStart;
    (void)dmaStart.now();
    const U32 timeoutUs = timeoutMs * 1000U;
    constexpr U32 MAX_DMA_POLL_ITERATIONS = 1000000U;  // hard backstop; the time check below is the real bound
    for (U32 i = 0; dmaBusy && (i < MAX_DMA_POLL_ITERATIONS); i++) {
        Os::RawTime now;
        (void)now.now();
        U32 elapsedUs = 0;
        (void)now.getDiffUsec(dmaStart, elapsedUs);
        if (elapsedUs >= timeoutUs) {
            break;
        }
    }
    return !dmaBusy;
}

}  // namespace

//! Address-phase NACK (no device answered) is reported via HAL_I2C_GetError(),
//! not the HAL_StatusTypeDef -- distinguishes I2C_ADDRESS_ERR from a
//! data-phase/bus I2C_WRITE_ERR/I2C_READ_ERR.
Drv::I2cStatus Stm32I2cDriver ::hwMasterTransmit(U16 devAddress, U8* data, U16 len) {
    FW_ASSERT(data != nullptr);

    // Re-resolved on every call (not cached in file-static state) so that
    // multiple Stm32I2cDriver instances -- different buses -- can be open
    // at the same time without sharing any mutable HAL state.
    I2C_HandleTypeDef* const halHandle = toHalHandle(this->m_instance);
    FW_ASSERT(halHandle != nullptr);

    HAL_StatusTypeDef status;
    if (this->m_transferMode == TransferMode::POLLED) {
        status = HAL_I2C_Master_Transmit(halHandle, static_cast<uint16_t>(devAddress << 1U), data, len,
                                          TRANSACTION_TIMEOUT_MS);
    } else {
        Stm32::AssertDmaSafe(data, len);
        Stm32::CleanDCacheForDma(data, len);
        this->m_dmaBusy = true;
        this->m_dmaErrorCode = 0;
        status = HAL_I2C_Master_Transmit_DMA(halHandle, static_cast<uint16_t>(devAddress << 1U), data, len);
        if (status == HAL_OK) {
            if (!waitForI2cDma(this->m_dmaBusy, TRANSACTION_TIMEOUT_MS)) {
                (void)HAL_I2C_Master_Abort_IT(halHandle, static_cast<uint16_t>(devAddress << 1U));
                this->m_dmaBusy = false;
                status = HAL_TIMEOUT;
            } else {
                status = (this->m_dmaErrorCode == 0) ? HAL_OK : HAL_ERROR;
            }
        } else {
            this->m_dmaBusy = false;
        }
    }

    if (status == HAL_OK) {
        return Drv::I2cStatus::I2C_OK;
    }
    Fw::LogStringArg _op("Master_Transmit");
    this->log_WARNING_HI_HalError(_op, devAddress, static_cast<I32>(status));
    return ((HAL_I2C_GetError(halHandle) & HAL_I2C_ERROR_AF) != 0U) ? Drv::I2cStatus::I2C_ADDRESS_ERR
                                                                     : Drv::I2cStatus::I2C_WRITE_ERR;
}

Drv::I2cStatus Stm32I2cDriver ::hwMasterReceive(U16 devAddress, U8* data, U16 len) {
    FW_ASSERT(data != nullptr);

    I2C_HandleTypeDef* const halHandle = toHalHandle(this->m_instance);
    FW_ASSERT(halHandle != nullptr);

    HAL_StatusTypeDef status;
    if (this->m_transferMode == TransferMode::POLLED) {
        status = HAL_I2C_Master_Receive(halHandle, static_cast<uint16_t>(devAddress << 1U), data, len,
                                         TRANSACTION_TIMEOUT_MS);
    } else {
        Stm32::AssertDmaSafe(data, len);
        this->m_dmaBusy = true;
        this->m_dmaErrorCode = 0;
        status = HAL_I2C_Master_Receive_DMA(halHandle, static_cast<uint16_t>(devAddress << 1U), data, len);
        if (status == HAL_OK) {
            if (!waitForI2cDma(this->m_dmaBusy, TRANSACTION_TIMEOUT_MS)) {
                (void)HAL_I2C_Master_Abort_IT(halHandle, static_cast<uint16_t>(devAddress << 1U));
                this->m_dmaBusy = false;
                status = HAL_TIMEOUT;
            } else {
                status = (this->m_dmaErrorCode == 0) ? HAL_OK : HAL_ERROR;
                Stm32::InvalidateDCacheForDma(data, len);
            }
        } else {
            this->m_dmaBusy = false;
        }
    }

    if (status == HAL_OK) {
        return Drv::I2cStatus::I2C_OK;
    }
    Fw::LogStringArg _op("Master_Receive");
    this->log_WARNING_HI_HalError(_op, devAddress, static_cast<I32>(status));
    return ((HAL_I2C_GetError(halHandle) & HAL_I2C_ERROR_AF) != 0U) ? Drv::I2cStatus::I2C_ADDRESS_ERR
                                                                     : Drv::I2cStatus::I2C_READ_ERR;
}

}  // namespace Stm32