// ======================================================================
// \title  Stm32UartDriver.cpp
// \author ivanlara
// \brief  HAL boundary for the STM32H7 USART/UART DMA-backed byte stream
//         driver (real hardware implementation, stm32h7 target only).
//         This is the only file in this driver allowed to include
//         CacheMaintenance.hpp/dma.h/usart.h -- see
//         Stm32UartDriverStub.cpp for the host unit-test stand-in.
// ======================================================================

#include <fprime-stm32/Drv/STM32UartDriver/Stm32UartDriver.hpp>

#include "CacheMaintenance.hpp"
#include "dma.h"
#include "usart.h"

namespace {

//! Callback registry: the HAL callbacks below are free functions with no
//! user-context pointer, only a raw UART_HandleTypeDef*, so mapping back to
//! "which Stm32UartDriver instance owns this handle" needs a table rather
//! than a single cached pointer -- that's what lets multiple instances
//! (e.g. USART1 for the ground link and USART2 for a second radio) be open
//! at the same time without one instance's ISR traffic misrouting to
//! another's. Indexed by UsartInstance's own cardinality, matching the
//! "named capacity constant" convention already used elsewhere in this
//! codebase (e.g. Os::Baremetal::TaskRunner::TASK_CAPACITY).
constexpr FwSizeType USART_INSTANCE_CAPACITY = 8;

struct UartRegistryEntry {
    UART_HandleTypeDef* handle = nullptr;
    Stm32::Stm32UartDriver* component = nullptr;
};

UartRegistryEntry s_uartRegistry[USART_INSTANCE_CAPACITY];

//! Convert a HAL-free UsartInstance to the corresponding HAL handle.
UART_HandleTypeDef* toHalHandle(Stm32::UsartInstance instance) {
    //! The cases for each USART/UART instance. If your project uses additional instances,
    //! you need to add them here and ensure the corresponding HAL handle is returned, after
    //! you update the files from CubeMX autogenerated code into lib/fprime-stm32/src/usart.c.
    UART_HandleTypeDef* deviceHandle = nullptr;

    switch (instance) {
        case Stm32::UsartInstance::Usart1:
            #if USART1_UART_INSTANCE
            return deviceHandle = &huart1;
            #endif
            break;
        case Stm32::UsartInstance::Usart2:
            #if USART2_UART_INSTANCE
            return deviceHandle = &huart2;
            #endif
            break;
        case Stm32::UsartInstance::Usart3:
            #if USART3_UART_INSTANCE
            return deviceHandle = &huart3;
            #endif
            break;
        case Stm32::UsartInstance::Uart4:
            #if UART4_INSTANCE
            return deviceHandle = &huart4;
            #endif
            break;
        case Stm32::UsartInstance::Uart5:
            #if UART5_INSTANCE
            return deviceHandle = &huart5;
            #endif
            break;
        case Stm32::UsartInstance::Usart6:
            #if USART6_UART_INSTANCE
            return deviceHandle = &huart6;
            #endif
            break;
        case Stm32::UsartInstance::Uart7:
            #if UART7_INSTANCE
            return deviceHandle = &huart7;
            #endif
            break;
        case Stm32::UsartInstance::Uart8:
            #if UART8_INSTANCE
            return deviceHandle = &huart8;
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
    // Return the device handle, which will be nullptr if the instance was not found.
    return deviceHandle;
}

//! Map a HAL-free UsartInstance to its NVIC interrupt number.
IRQn_Type toIrqn(Stm32::UsartInstance instance) {
    switch (instance) {
        case Stm32::UsartInstance::Usart1:
            return USART1_IRQn;
        case Stm32::UsartInstance::Usart2:
            return USART2_IRQn;
        case Stm32::UsartInstance::Usart3:
            return USART3_IRQn;
        case Stm32::UsartInstance::Uart4:
            return UART4_IRQn;
        case Stm32::UsartInstance::Uart5:
            return UART5_IRQn;
        case Stm32::UsartInstance::Usart6:
            return USART6_IRQn;
        case Stm32::UsartInstance::Uart7:
            return UART7_IRQn;
        case Stm32::UsartInstance::Uart8:
            return UART8_IRQn;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            return USART1_IRQn;
    }
}

//! Call the CubeMX-generated init function for the selected instance.
void callInstanceInit(Stm32::UsartInstance instance) {
    //! The cases for each USART/UART instance. If your project uses additional instances,
    //! you need to add the correspondent Initialization fuction, just after you update the
    //! files from CubeMX autogenerated code into lib/fprime-stm32/src/usart.c.
    switch (instance) {
        case Stm32::UsartInstance::Usart1:
            #if USART1_UART_INSTANCE
            MX_USART1_UART_Init();
            #endif
            break;
        case Stm32::UsartInstance::Usart2:
            #if USART2_UART_INSTANCE
            MX_USART2_UART_Init();
            #endif
            break;
        case Stm32::UsartInstance::Usart3:
            #if USART3_UART_INSTANCE
            MX_USART3_UART_Init();
            #endif
            break;
        case Stm32::UsartInstance::Uart4:
            #if UART4_INSTANCE
            MX_UART4_Init();
            #endif
            break;
        case Stm32::UsartInstance::Uart5:
            #if UART5_INSTANCE
            MX_UART5_Init();
            #endif
            break;
        case Stm32::UsartInstance::Usart6:
            #if USART6_UART_INSTANCE
            MX_USART6_UART_Init();
            #endif
            break;
        case Stm32::UsartInstance::Uart7:
            #if UART7_INSTANCE
            MX_UART7_Init();
            #endif
            break;
        case Stm32::UsartInstance::Uart8:
            #if UART8_INSTANCE
            MX_UART8_Init();
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
}

}  // namespace

namespace {

//! Look up which live Stm32UartDriver instance (if any) owns `huart`, by
//! linear scan of the small (<=8-entry) registry. Negligible ISR cost, and
//! the only way to resolve identity: the HAL calls these callbacks with no
//! instance/context argument, only the raw handle pointer.
Stm32::Stm32UartDriver* findUartComponent(UART_HandleTypeDef* huart) {
    for (FwSizeType i = 0; i < USART_INSTANCE_CAPACITY; i++) {
        if (s_uartRegistry[i].handle == huart && s_uartRegistry[i].component != nullptr) {
            return s_uartRegistry[i].component;
        }
    }
    return nullptr;
}

}  // namespace

extern "C" void HAL_UART_TxCpltCallback(UART_HandleTypeDef* huart) {
    FW_ASSERT(huart != nullptr);
    Stm32::Stm32UartDriver* const component = findUartComponent(huart);
    if (component != nullptr) {
        component->signalTxComplete();
    }
}

extern "C" void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef* huart, uint16_t Size) {
    FW_ASSERT(huart != nullptr);
    Stm32::Stm32UartDriver* const component = findUartComponent(huart);
    if (component != nullptr) {
        component->signalRxChunk(Size);
    }
}

extern "C" void HAL_UART_ErrorCallback(UART_HandleTypeDef* huart) {
    FW_ASSERT(huart != nullptr);
    Stm32::Stm32UartDriver* const component = findUartComponent(huart);
    if (component != nullptr) {
        component->signalUartError(huart->ErrorCode);
    }
}

namespace Stm32 {

bool Stm32UartDriver ::hwOpen(UsartInstance instance, U32 preemptPriority, U32 subPriority, U32 requestedBaudRate,
                               U32& outActualBaudRate) {
    (void)requestedBaudRate;  // not used to configure the peripheral: CubeMX fixes the baud in usart.c

    UART_HandleTypeDef* const halHandle = toHalHandle(instance);
    FW_ASSERT(halHandle != nullptr, static_cast<FwAssertArgType>(instance));
    const IRQn_Type irqn = toIrqn(instance);

    // DMA1 clock/NVIC must be enabled before HAL_UART_MspInit() (invoked from
    // MX_USARTn_UART_Init() -> HAL_UART_Init()) links and initializes the
    // selected instance's TX/RX DMA streams.
    MX_DMA_Init();
    callInstanceInit(instance);

    // Not configured by CubeMX: the USART global interrupt is required for
    // HAL_UARTEx_ReceiveToIdle_DMA()'s idle-line detection, which only the
    // USART peripheral (not the DMA streams) can signal.
    HAL_NVIC_SetPriority(irqn, preemptPriority, subPriority);
    HAL_NVIC_EnableIRQ(irqn);

    // Registered by instance index (bounds-safe: the enum itself can't
    // index outside the table), not a single shared pointer -- this is
    // what makes a second, simultaneously-open instance safe.
    FW_ASSERT(static_cast<FwSizeType>(instance) < USART_INSTANCE_CAPACITY,
              static_cast<FwAssertArgType>(instance));
    s_uartRegistry[static_cast<FwSizeType>(instance)] = {halHandle, this};

    this->m_txDmaBusy = false;
    this->m_rxChunkReady = false;
    this->m_rxChunkLen = 0;
    this->m_uartErrorPending = false;
    this->m_uartErrorCode = 0;

    const I32 status = this->hwRestartRx();
    if (status != HAL_OK) {
        Fw::LogStringArg _op("ReceiveToIdle_DMA");
        this->log_WARNING_HI_HalError(_op, status);
        return false;
    }

    outActualBaudRate = halHandle->Init.BaudRate;
    return true;
}

bool Stm32UartDriver ::hwStartTx(const U8* data, FwSizeType len) {
    UART_HandleTypeDef* const halHandle = toHalHandle(this->m_instance);
    FW_ASSERT(halHandle != nullptr);
    Stm32::CleanDCacheForDma(data, len);
    const HAL_StatusTypeDef status =
        HAL_UART_Transmit_DMA(halHandle, const_cast<U8*>(data), static_cast<uint16_t>(len));
    if (status != HAL_OK) {
        Fw::LogStringArg _op("Transmit_DMA");
        this->log_WARNING_HI_HalError(_op, static_cast<I32>(status));
        return false;
    }
    return true;
}

void Stm32UartDriver ::hwAbortTx() {
    (void)HAL_UART_AbortTransmit(toHalHandle(this->m_instance));
}

void Stm32UartDriver ::hwInvalidateRxStaging() {
    Stm32::InvalidateDCacheForDma(this->m_rxStaging, RX_STAGING_SIZE);
}

I32 Stm32UartDriver ::hwRestartRx() {
    UART_HandleTypeDef* const halHandle = toHalHandle(this->m_instance);
    FW_ASSERT(halHandle != nullptr);
    const HAL_StatusTypeDef status =
        HAL_UARTEx_ReceiveToIdle_DMA(halHandle, this->m_rxStaging, static_cast<uint16_t>(RX_STAGING_SIZE));
    return static_cast<I32>(status);
}

void Stm32UartDriver ::hwAbortRx() {
    (void)HAL_UART_AbortReceive(toHalHandle(this->m_instance));
}

void Stm32UartDriver ::hwClearUartError() {
    UART_HandleTypeDef* const halHandle = toHalHandle(this->m_instance);
    FW_ASSERT(halHandle != nullptr);
    halHandle->ErrorCode = HAL_UART_ERROR_NONE;
}

void Stm32UartDriver ::hwClassifyUartError(U32 errorCode, bool& isRxAffecting, bool& isDmaAffecting) {
    isRxAffecting =
        (errorCode & (HAL_UART_ERROR_ORE | HAL_UART_ERROR_FE | HAL_UART_ERROR_PE | HAL_UART_ERROR_NE)) != 0U;
    isDmaAffecting = (errorCode & HAL_UART_ERROR_DMA) != 0U;
}

}  // namespace Stm32